# Generated by Django 6.0.3 on 2026-03-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='type',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(),
        ),
    ]
